generatorName: typescript-fetch
outputDir: mit-learn-api-clients/src/typescript/mit-learn-api-fetch/src/v1
inputSpec: mit-learn/openapi/specs/v1.yaml
ignoreFileOverride: mit-learn-api-clients/.openapi-generator-ignore
additionalProperties:
  globalProperty: apis,models
  paramNaming: original
  useSingleRequestParameter: true
